name = "neil-emmett-writer"
main = "worker.js"
compatibility_date = "2024-09-01"
account_id = "d5cb3e4213b6aa69dbc2feb1499af77a"

routes = [
  { pattern = "jdpwriter.com/neil*", zone_name = "jdpwriter.com" },
  { pattern = "www.jdpwriter.com/neil*", zone_name = "jdpwriter.com" },
  { pattern = "jdpwriter.com/api/neil*", zone_name = "jdpwriter.com" },
  { pattern = "www.jdpwriter.com/api/neil*", zone_name = "jdpwriter.com" },
  { pattern = "jdpwriter.com/neil-emmett*", zone_name = "jdpwriter.com" },
  { pattern = "www.jdpwriter.com/neil-emmett*", zone_name = "jdpwriter.com" }
]

workers_dev = true

[vars]
PESATROUTER_API_KEY = "sk-pesat-3c2f89bd9a72302375f8e10ef9eba726891a81513f907dfb"
PESATROUTER_MODEL = "pesat-pro"
PESATROUTER_URL = "https://api.pesatrouter.com/v1/chat/completions"
